CrusDe: plugin_src/load_history/boxcar.c File Reference
plugin_src/load_history/boxcar.c File Reference
#include <stdio.h>
#include <math.h>
#include "crusde_api.h"
Functions
const char * get_name ()
const char * get_version ()
const char * get_authors ()
PluginCategory get_category ()
const char * get_description ()
void request_plugins ()
void register_output_fields ()
void run ()
void clear ()
void init ()
void register_parameter ()
double get_value_at (unsigned int t)
Variables
double * p_start [100]
double * p_end [100]
int my_id = 0
Detailed Description
Function Documentation
void clear ()
freeing mallocs
const char* get_authors ()
PluginCategory get_category ()
References LOADHISTORY_PLUGIN.
const char* get_description ()
const char* get_name ()
double get_value_at (unsigned int t)
References crusde_get_current_load_component(), my_id, p_end, and p_start.
const char* get_version ()
void init ()
empty
void register_output_fields ()
empty
void register_parameter ()
Register parameters this load function claims from the input.
References crusde_get_current_load_component(), crusde_register_param_double(), get_category(), my_id, p_end, and p_start.
void request_plugins ()
empty
void run ()
empty
Variable Documentation
int my_id = 0
double* p_end[100]
pointer to end interval values
Referenced by get_value_at(), and register_parameter().
double* p_start[100]
pointer to start interval values
Referenced by get_value_at(), and register_parameter().