CrusDe: StrXML Class Reference
StrXML Class Reference
#include <XMLHandler.h>
Public Member Functions
StrXML (const char *const orig)
StrXML (const XMLCh *const orig)
StrXML (const string &orig)
~StrXML () throw ()
const XMLCh * xmlStr () const throw ()
const char * cStr () const throw ()
const string cppStr () const throw ()
Private Attributes
char * cstring
XMLCh * xmlstring
string cppstring
Constructor & Destructor Documentation
StrXML::StrXML (const char *const orig)
StrXML::StrXML (const XMLCh *const orig)
StrXML::StrXML (const string & orig)
StrXML::~StrXML () throw ()
References cstring, and xmlstring.
Member Function Documentation
const string StrXML::cppStr () const throw ()
References cppstring.
Referenced by ExperimentManager::addMetaData(), ExperimentManager::childrenToString(), InputHandler::getGreenJobMap(), InputHandler::getLoadFunctionList(), InputHandler::getPostProcessorNameList(), and InputHandler::jobExists().
const char * StrXML::cStr () const throw ()
References cstring.
Referenced by ExperimentManager::childrenToString(), XMLHandler::getActualID(), InputHandler::getGreenJobMap(), and InputHandler::getLoadFunctionList().
const XMLCh * StrXML::xmlStr () const throw ()
References xmlstring.
Referenced by ExperimentManager::addEntry(), ExperimentManager::addMetaData(), PluginManager::addToDB(), ExperimentManager::childrenToString(), XMLHandler::getActualID(), InputHandler::getAttributeValueByName(), PluginManager::getDependencies(), PluginManager::getDependents(), PluginManager::getEntryById(), ExperimentManager::getEntryById(), PluginManager::getEntryDetails(), PluginManager::getEntryMap(), ExperimentManager::getEntryMap(), InputHandler::getFileName(), InputHandler::getGreenJobMap(), InputHandler::getGridSize(), InputHandler::getKernelPlugin(), InputHandler::getLoadFunctionList(), InputHandler::getLoadPlugin(), InputHandler::getOutputPlugin(), PluginManager::getParameters(), InputHandler::getPostProcessorNameList(), InputHandler::getRegion(), InputHandler::getResultFileName(), InputHandler::getTimeIncrement(), InputHandler::getTimeSteps(), XMLHandler::getValueOfNode(), InputHandler::initParamsFromDOM(), PluginManager::isInDB(), and InputHandler::jobExists().
Member Data Documentation
string StrXML::cppstring [private]
Referenced by cppStr().
char* StrXML::cstring [private]
Referenced by cStr(), and ~StrXML().
XMLCh* StrXML::xmlstring [private]
Referenced by xmlStr(), and ~StrXML().
The documentation for this class was generated from the following files:
XMLHandler.h
XMLHandler.cpp