CrusDe: TreeItem Class Reference
TreeItem Class Reference
#include <Qt_TreeItem.h>
Public Member Functions
TreeItem (int ID, string data, TreeItem *parent=0)
~TreeItem ()
void appendChild (TreeItem *child)
TreeItem * child (int row)
int childCount () const
int columnCount () const
QVariant data (int column) const
int row () const
TreeItem * parent ()
int getID () const
void removeChild (int i)
Private Attributes
QList< TreeItem * > childItems
string itemData
TreeItem * parentItem
int id
Constructor & Destructor Documentation
TreeItem::TreeItem (int ID, string data, TreeItem * parent = 0)
References itemData, and parentItem.
TreeItem::~TreeItem ()
References childItems.
Member Function Documentation
void TreeItem::appendChild (TreeItem * child)
References childItems.
Referenced by TreeModel::setupModelData().
TreeItem * TreeItem::child (int row)
References childItems.
Referenced by TreeModel::index(), and TreeModel::indexOfLatestItem().
int TreeItem::childCount () const
References childItems.
Referenced by TreeModel::rowCount().
int TreeItem::columnCount () const
Referenced by TreeModel::columnCount().
QVariant TreeItem::data (int column) const
References itemData.
Referenced by TreeModel::data(), and TreeModel::headerData().
int TreeItem::getID () const
References id.
Referenced by TreeModel::getID().
TreeItem * TreeItem::parent ()
References parentItem.
Referenced by TreeModel::parent().
void TreeItem::removeChild (int i)
References childItems.
Referenced by TreeModel::removeRows(), and TreeModel::setupModelData().
int TreeItem::row () const
References childItems, and parentItem.
Referenced by TreeModel::parent().
Member Data Documentation
QList<TreeItem*> TreeItem::childItems [private]
Referenced by appendChild(), child(), childCount(), removeChild(), row(), and ~TreeItem().
int TreeItem::id [private]
Referenced by getID().
string TreeItem::itemData [private]
Referenced by data(), and TreeItem().
TreeItem* TreeItem::parentItem [private]
Referenced by parent(), row(), and TreeItem().
The documentation for this class was generated from the following files:
Qt_TreeItem.h
Qt_TreeItem.cpp