CrusDe: Dialog Class Reference
Dialog Class Reference
#include <Dialog.h>
Public Member Functions
Dialog (DatabaseManager *, string title, bool addbutton)
Private Slots
virtual void deleteClicked ()
virtual void addClicked ()
virtual void quitClicked ()
virtual void showDetails (QModelIndex)
Private Member Functions
void setModelData ()
Private Attributes
DatabaseManager * manager
QTextEdit details
QHBoxLayout layout_main
QVBoxLayout layout_ctrlbutt
TreeModel treemodel
QTreeView treeview
QPushButton * butt_QUIT
QPushButton * butt_DELETE
QPushButton * butt_ADD
QString current_dir
Constructor & Destructor Documentation
Dialog::Dialog (DatabaseManager * manager_, string title, bool addbutton)
References addClicked(), butt_ADD, butt_DELETE, butt_QUIT, current_dir, deleteClicked(), details, layout_ctrlbutt, layout_main, quitClicked(), setModelData(), showDetails(), treemodel, and treeview.
Member Function Documentation
void Dialog::addClicked () [private, virtual, slot]
References DatabaseManager::addEntry(), current_dir, DatabaseManager::getLastAddedID(), i, TreeModel::indexOfLatestItem(), manager, setModelData(), showDetails(), treemodel, and treeview.
Referenced by Dialog().
void Dialog::deleteClicked () [private, virtual, slot]
References DatabaseManager::deleteEntry(), details, TreeModel::getID(), manager, TreeModel::removeRows(), treemodel, and treeview.
Referenced by Dialog().
void Dialog::quitClicked () [private, virtual, slot]
Referenced by Dialog().
void Dialog::setModelData () [private]
References DatabaseManager::getEntryMap(), manager, TreeModel::setupModelData(), treemodel, and treeview.
Referenced by addClicked(), and Dialog().
void Dialog::showDetails (QModelIndex index) [private, virtual, slot]
References details, DatabaseManager::getEntryDetails(), TreeModel::getID(), manager, and treemodel.
Referenced by addClicked(), and Dialog().
Member Data Documentation
QPushButton * Dialog::butt_ADD [private]
Referenced by Dialog().
QPushButton * Dialog::butt_DELETE [private]
Referenced by Dialog().
QPushButton* Dialog::butt_QUIT [private]
Referenced by Dialog().
QString Dialog::current_dir [private]
Referenced by addClicked(), and Dialog().
QTextEdit Dialog::details [private]
Referenced by deleteClicked(), Dialog(), and showDetails().
QVBoxLayout Dialog::layout_ctrlbutt [private]
Referenced by Dialog().
QHBoxLayout Dialog::layout_main [private]
Referenced by Dialog().
DatabaseManager* Dialog::manager [private]
Referenced by addClicked(), deleteClicked(), setModelData(), and showDetails().
TreeModel Dialog::treemodel [private]
Referenced by addClicked(), deleteClicked(), Dialog(), setModelData(), and showDetails().
QTreeView Dialog::treeview [private]
Referenced by addClicked(), deleteClicked(), Dialog(), and setModelData().
The documentation for this class was generated from the following files:
Dialog.h
Dialog.cpp