CrusDe: DataOutPlugin Class Reference
DataOutPlugin Class Reference
#include <DataOutPlugin.h>
Public Member Functions
DataOutPlugin (const string=NULL)
virtual ~DataOutPlugin ()
virtual void load (const string) throw (FileNotFound, LibHandleError)
void setModelData (double **)
void setMetaData ()
Private Types
typedef double(* value_t)(double **, int, int)
Private Member Functions
DataOutPlugin (const DataOutPlugin &x)
Private Attributes
value_t func_value
Member Typedef Documentation
typedef double(* DataOutPlugin::value_t)(double **, int, int) [private]
Constructor & Destructor Documentation
DataOutPlugin::DataOutPlugin (const DataOutPlugin & x) [private]
hidden copy constructor - we do not want to accidentially copy objects
DataOutPlugin::DataOutPlugin (const string _name = NULL)
DataOutPlugin::~DataOutPlugin () [virtual]
References crusde_debug(), and Plugin::name.
Member Function Documentation
void DataOutPlugin::load (const string) throw (FileNotFound, LibHandleError) [virtual]
Reimplemented from Plugin.
References crusde_debug(), and Plugin::load().
Referenced by SimulationCore::init().
void DataOutPlugin::setMetaData () [inline]
void DataOutPlugin::setModelData (double ** result)
References crusde_debug(), func_value, and Plugin::name.
Referenced by SimulationCore::setModelData().
Member Data Documentation
value_t DataOutPlugin::func_value [private]
Referenced by setModelData().
The documentation for this class was generated from the following files:
DataOutPlugin.h
DataOutPlugin.cpp