CrusDe: ExperimentManager Class Reference
ExperimentManager Class Reference
#include <ExperimentManager.h>
Public Member Functions
ExperimentManager (const char *)
virtual ~ExperimentManager ()
virtual void run ()
start the manager
virtual void addEntry (string ident, DOMNode *parent=0)
add database entry
virtual string getEntryDetails (int id)
returns a formatted string for display containing all details listed for plugin 'id' in db
virtual multimap< string, map
< int, string > > getEntryMap ()
returns a formatted string for display containing all details listed for plugin 'id' in db
virtual bool deleteEntry (int id)
removes plugin from database. checks before, whether any other plugin depends on ID
void addMetaData (string)
Private Member Functions
ExperimentManager (const ExperimentManager &x)
hidden copy constructor - we do not want to accidentially copy objects
ExperimentManager const & operator= (ExperimentManager const &rvalue)
hidden assignment operator - we do not want to accidentially copy objects
string childrenToString (DOMNode *n)
string childrenToString (DOMNode *n, const XMLCh *tag)
DOMNode * getEntryById (int id)
Private Attributes
DOMNode * actual_experiment
Detailed Description
manages the experiment database of the actual user
Constructor & Destructor Documentation
ExperimentManager::ExperimentManager (const ExperimentManager & x) [private]
hidden copy constructor - we do not want to accidentially copy objects
ExperimentManager::ExperimentManager (const char * db)
References crusde_debug().
virtual ExperimentManager::~ExperimentManager () [inline, virtual]
Member Function Documentation
void ExperimentManager::addEntry (string result_file, DOMNode * exp_root = 0) [virtual]
add database entry
add experiment
Implements DatabaseManager.
References actual_experiment, addMetaData(), XMLHandler::ATTR_id, crusde_warning(), XMLHandler::doc, XMLHandler::getActualID(), SimulationCore::instance(), DatabaseManager::last_id, stringify(), SimulationCore::terminate(), XMLHandler::writeXML(), and StrXML::xmlStr().
Referenced by SimulationCore::exec().
void ExperimentManager::addMetaData (string filename)
References actual_experiment, XMLHandler::ATTR_date, XMLHandler::ATTR_gmtime, XMLHandler::ATTR_id, XMLHandler::ATTR_localtime, XMLHandler::ATTR_name, XMLHandler::ATTR_user, XMLHandler::ATTR_value, StrXML::cppStr(), XMLHandler::doc, XMLHandler::getActualID(), stringify(), XMLHandler::TAG_file, and StrXML::xmlStr().
Referenced by addEntry().
string ExperimentManager::childrenToString (DOMNode * n, const XMLCh * tag) [private]
build a detailed string
References XMLHandler::ATTR_name, XMLHandler::ATTR_value, StrXML::cppStr(), StrXML::cStr(), i, XMLHandler::TAG_plugin, and StrXML::xmlStr().
string ExperimentManager::childrenToString (DOMNode * n) [private]
References XMLHandler::TAG_file, XMLHandler::TAG_parameter, XMLHandler::TAG_plugin, XMLHandler::TAG_region, and StrXML::xmlStr().
Referenced by getEntryDetails().
bool ExperimentManager::deleteEntry (int id) [virtual]
removes plugin from database. checks before, whether any other plugin depends on ID
delete experiment
Implements DatabaseManager.
References crusde_warning(), XMLHandler::doc, getEntryById(), and XMLHandler::writeXML().
DOMNode * ExperimentManager::getEntryById (int id) [private]
References XMLHandler::ATTR_id, XMLHandler::doc, i, stringify(), XMLHandler::TAG_experiment, and StrXML::xmlStr().
Referenced by deleteEntry(), and getEntryDetails().
string ExperimentManager::getEntryDetails (int id) [virtual]
returns a formatted string for display containing all details listed for plugin 'id' in db
get Experiments
Implements DatabaseManager.
References childrenToString(), and getEntryById().
multimap< string, map< int, string > > ExperimentManager::getEntryMap () [virtual]
returns a formatted string for display containing all details listed for plugin 'id' in db
get Experiments
Implements DatabaseManager.
References XMLHandler::ATTR_date, XMLHandler::ATTR_gmtime, XMLHandler::ATTR_id, XMLHandler::ATTR_name, XMLHandler::ATTR_user, XMLHandler::doc, i, XMLHandler::TAG_experiment, and StrXML::xmlStr().
ExperimentManager const& ExperimentManager::operator= (ExperimentManager const & rvalue) [private]
hidden assignment operator - we do not want to accidentially copy objects
void ExperimentManager::run () [virtual]
start the manager
start gui
Implements DatabaseManager.
References DatabaseManager::is_initialized, and DatabaseManager::runDialogWindow().
Referenced by SimulationCore::runExperimentManager().
Member Data Documentation
DOMNode* ExperimentManager::actual_experiment [private]
Referenced by addEntry(), and addMetaData().
The documentation for this class was generated from the following files:
ExperimentManager.h
ExperimentManager.cpp