CrusDe: ParamWrapper Class Reference
ParamWrapper Class Reference
#include <ParamWrapper.h>
Public Member Functions
ParamWrapper ()
~ParamWrapper ()
bool isString ()
bool isDouble ()
void setValue (string)
void setValue (double)
char ** newString (char *=NULL)
double * newDouble (double=0.0)
char ** stringValue ()
double * doubleValue ()
bool isOptional ()
void setOptional (bool)
Private Attributes
string * string_param
double * double_param
bool optional
char * cStr
Detailed Description
provides a plug-in interface, but overrides most of the functions since it holds a list of loads.
Constructor & Destructor Documentation
ParamWrapper::ParamWrapper ()
ParamWrapper::~ParamWrapper ()
References cStr, double_param, free(), and string_param.
Member Function Documentation
double * ParamWrapper::doubleValue ()
References double_param.
bool ParamWrapper::isDouble ()
References double_param.
Referenced by setValue().
bool ParamWrapper::isOptional ()
References optional.
bool ParamWrapper::isString ()
References string_param.
Referenced by setValue().
double * ParamWrapper::newDouble (double val = 0.0)
References crusde_error(), double_param, and string_param.
Referenced by crusde_register_optional_param_double(), and crusde_register_param_double().
char ** ParamWrapper::newString (char * val = NULL)
References crusde_error(), cStr, double_param, and string_param.
Referenced by crusde_register_optional_param_string(), and crusde_register_param_string().
void ParamWrapper::setOptional (bool value)
References optional.
Referenced by crusde_register_optional_param_double(), crusde_register_optional_param_string(), crusde_register_param_double(), and crusde_register_param_string().
void ParamWrapper::setValue (double value)
References crusde_error(), double_param, and isDouble().
void ParamWrapper::setValue (string value)
References crusde_error(), cStr, isString(), and string_param.
char ** ParamWrapper::stringValue ()
References cStr.
Member Data Documentation
char* ParamWrapper::cStr [private]
Referenced by newString(), setValue(), stringValue(), and ~ParamWrapper().
double* ParamWrapper::double_param [private]
Referenced by doubleValue(), isDouble(), newDouble(), newString(), setValue(), and ~ParamWrapper().
bool ParamWrapper::optional [private]
Referenced by isOptional(), and setOptional().
string* ParamWrapper::string_param [private]
Referenced by isString(), newDouble(), newString(), setValue(), and ~ParamWrapper().
The documentation for this class was generated from the following files:
ParamWrapper.h
ParamWrapper.cpp