CrusDe: GreensFunction Class Reference
GreensFunction Class Reference
#include <GreensFunction.h>
Public Member Functions
GreensFunction (const string)
virtual ~GreensFunction ()
void setFirstJob ()
bool nextJob ()
bool isLastJob ()
string job ()
int getValueArrayAt (double **, int, int)
void load (map< string, string >)
void unload () throw (LibHandleError)
void registerParameter ()
void registerOutputFields ()
void requestPlugins ()
void init ()
void release ()
Private Member Functions
GreensFunction (const GreensFunction &x)
Private Attributes
map< string, GreenPlugin * >
::iterator map_iter
map< string, GreenPlugin * > pl_green_map
Detailed Description
provides a plug-in interface, but overrides most of the functions since it holds a list of greens functions.
we don't need an 'id' counter here! It was necessary in the LoadFunction since all the loads could and should have different parameter values whereas the Green's functions are allowed to have only one identical parameter set.
Constructor & Destructor Documentation
GreensFunction::GreensFunction (const GreensFunction & x) [private]
hidden copy constructor - we do not want to accidentially copy objects
GreensFunction::GreensFunction (const string _name)
GreensFunction::~GreensFunction () [virtual]
References map_iter, and pl_green_map.
Member Function Documentation
int GreensFunction::getValueArrayAt (double ** d, int x, int y)
References map_iter.
Referenced by crusde_get_green_at().
void GreensFunction::init () [virtual]
Reimplemented from Plugin.
References map_iter, and pl_green_map.
Referenced by SimulationCore::init().
bool GreensFunction::isLastJob ()
References map_iter, and pl_green_map.
Referenced by SimulationCore::exec().
string GreensFunction::job ()
References map_iter.
Referenced by SimulationCore::currentJob(), and SimulationCore::exec().
void GreensFunction::load (map< string, string > job_map)
References SimulationCore::abort(), crusde_warning(), SimulationCore::instance(), GreenPlugin::load(), and pl_green_map.
Referenced by SimulationCore::init().
bool GreensFunction::nextJob ()
References map_iter, and pl_green_map.
Referenced by SimulationCore::exec().
void GreensFunction::registerOutputFields () [virtual]
Reimplemented from Plugin.
References map_iter, and pl_green_map.
Referenced by SimulationCore::init().
void GreensFunction::registerParameter () [virtual]
Reimplemented from Plugin.
References map_iter, and pl_green_map.
Referenced by SimulationCore::init().
void GreensFunction::release () [virtual]
Reimplemented from Plugin.
References map_iter, and pl_green_map.
Referenced by SimulationCore::terminate().
void GreensFunction::requestPlugins () [virtual]
Reimplemented from Plugin.
References map_iter, and pl_green_map.
Referenced by SimulationCore::init().
void GreensFunction::setFirstJob ()
References map_iter, and pl_green_map.
Referenced by SimulationCore::exec().
void GreensFunction::unload () throw (LibHandleError) [virtual]
Reimplemented from Plugin.
References map_iter, and pl_green_map.
Referenced by SimulationCore::terminate().
Member Data Documentation
map<string, GreenPlugin*>::iterator GreensFunction::map_iter [private]
Referenced by getValueArrayAt(), init(), isLastJob(), job(), nextJob(), registerOutputFields(), registerParameter(), release(), requestPlugins(), setFirstJob(), unload(), and ~GreensFunction().
map<string, GreenPlugin*> GreensFunction::pl_green_map [private]
Referenced by init(), isLastJob(), load(), nextJob(), registerOutputFields(), registerParameter(), release(), requestPlugins(), setFirstJob(), unload(), and ~GreensFunction().
The documentation for this class was generated from the following files:
GreensFunction.h
GreensFunction.cpp