CrusDe: LoadPlugin Class Reference
LoadPlugin Class Reference
#include <LoadPlugin.h>
Public Member Functions
LoadPlugin (const string=NULL)
virtual ~LoadPlugin ()
virtual void load (const string) throw (FileNotFound, LibHandleError)
double getValueAt (int, int)
load_exec_function getValueFunction ()
Private Member Functions
LoadPlugin (const LoadPlugin &x)
Private Attributes
load_exec_function func_value
Constructor & Destructor Documentation
LoadPlugin::LoadPlugin (const LoadPlugin & x) [private]
hidden copy constructor - we do not want to accidentially copy objects
LoadPlugin::LoadPlugin (const string _name = NULL)
LoadPlugin::~LoadPlugin () [virtual]
References crusde_debug(), and Plugin::name.
Member Function Documentation
double LoadPlugin::getValueAt (int x, int y)
References func_value, and Plugin::is_initialized.
load_exec_function LoadPlugin::getValueFunction ()
References func_value.
Referenced by SimulationCore::addLoadPlugin().
void LoadPlugin::load (const string) throw (FileNotFound, LibHandleError) [virtual]
Reimplemented from Plugin.
References crusde_debug(), and Plugin::load().
Referenced by SimulationCore::addLoadPlugin(), and LoadFunction::load().
Member Data Documentation
load_exec_function LoadPlugin::func_value [private]
Referenced by getValueAt(), and getValueFunction().
The documentation for this class was generated from the following files:
LoadPlugin.h
LoadPlugin.cpp