CrusDe: LoadFunction Class Reference
LoadFunction Class Reference
#include <LoadFunction.h>
Public Member Functions
LoadFunction (const string)
virtual ~LoadFunction ()
double getValueAt (int, int)
double getHistoryValueAt (int)
double getCrustalDecayValueAt (int)
boolean crustalDecayGiven ()
boolean loadHistoryGiven ()
void load (list< LoadFunctionElement * >)
void unload () throw (LibHandleError)
void registerParameter ()
void registerOutputFields ()
void requestPlugins ()
void init ()
void release ()
Private Member Functions
LoadFunction (const LoadPlugin &x)
Private Attributes
multimap< LoadPlugin *, pair
< LoadHistoryPlugin
*, CrustalDecayPlugin * >
>::iterator map_iter
multimap< LoadPlugin *, pair
< LoadHistoryPlugin
*, CrustalDecayPlugin * > > pl_load_map
double load_value
unsigned int load_function_component
Detailed Description
provides a plug-in interface, but overrides most of the functions since it holds a list of loads.
Constructor & Destructor Documentation
LoadFunction::LoadFunction (const LoadPlugin & x) [private]
hidden copy constructor - we do not want to accidentially copy objects
LoadFunction::LoadFunction (const string _name)
LoadFunction::~LoadFunction () [virtual]
References map_iter, and pl_load_map.
Member Function Documentation
boolean LoadFunction::crustalDecayGiven ()
References SimulationCore::getLoadFunctionComponent(), SimulationCore::instance(), map_iter, and pl_load_map.
Referenced by crusde_crustal_decay_given(), and getCrustalDecayValueAt().
double LoadFunction::getCrustalDecayValueAt (int td)
References crustalDecayGiven(), SimulationCore::getLoadFunctionComponent(), SimulationCore::instance(), map_iter, and pl_load_map.
Referenced by crusde_get_crustal_decay_at().
double LoadFunction::getHistoryValueAt (int td)
References SimulationCore::getLoadFunctionComponent(), SimulationCore::instance(), loadHistoryGiven(), map_iter, and pl_load_map.
Referenced by crusde_get_load_history_at().
double LoadFunction::getValueAt (int x, int y)
References SimulationCore::getLoadFunctionComponent(), SimulationCore::instance(), map_iter, and pl_load_map.
Referenced by crusde_get_load_at().
void LoadFunction::init () [virtual]
Reimplemented from Plugin.
References SimulationCore::instance(), load_function_component, map_iter, pl_load_map, and SimulationCore::setLoadFunctionComponent().
Referenced by SimulationCore::init().
void LoadFunction::load (list< LoadFunctionElement * > names)
References SimulationCore::abort(), SimulationCore::instance(), CrustalDecayPlugin::load(), LoadPlugin::load(), load_function_component, pl_load_map, CrustalDecayPlugin::setJobName(), and SimulationCore::setLoadFunctionComponent().
Referenced by SimulationCore::init().
boolean LoadFunction::loadHistoryGiven ()
References SimulationCore::getLoadFunctionComponent(), SimulationCore::instance(), map_iter, and pl_load_map.
Referenced by crusde_load_history_given(), and getHistoryValueAt().
void LoadFunction::registerOutputFields () [virtual]
Reimplemented from Plugin.
References SimulationCore::instance(), load_function_component, map_iter, pl_load_map, and SimulationCore::setLoadFunctionComponent().
void LoadFunction::registerParameter () [virtual]
Reimplemented from Plugin.
References SimulationCore::instance(), load_function_component, map_iter, pl_load_map, and SimulationCore::setLoadFunctionComponent().
Referenced by SimulationCore::init().
void LoadFunction::release () [virtual]
Reimplemented from Plugin.
References SimulationCore::instance(), load_function_component, map_iter, pl_load_map, and SimulationCore::setLoadFunctionComponent().
Referenced by SimulationCore::terminate().
void LoadFunction::requestPlugins () [virtual]
Reimplemented from Plugin.
References SimulationCore::instance(), load_function_component, map_iter, pl_load_map, and SimulationCore::setLoadFunctionComponent().
Referenced by SimulationCore::init().
void LoadFunction::unload () throw (LibHandleError) [virtual]
Reimplemented from Plugin.
References SimulationCore::instance(), load_function_component, map_iter, pl_load_map, and SimulationCore::setLoadFunctionComponent().
Referenced by SimulationCore::terminate().
Member Data Documentation
unsigned int LoadFunction::load_function_component [private]
Referenced by init(), load(), registerOutputFields(), registerParameter(), release(), requestPlugins(), and unload().
double LoadFunction::load_value [private]
multimap<LoadPlugin*, pair<LoadHistoryPlugin*, CrustalDecayPlugin*> >::iterator LoadFunction::map_iter [private]
Referenced by crustalDecayGiven(), getCrustalDecayValueAt(), getHistoryValueAt(), getValueAt(), init(), loadHistoryGiven(), registerOutputFields(), registerParameter(), release(), requestPlugins(), unload(), and ~LoadFunction().
multimap<LoadPlugin*, pair<LoadHistoryPlugin*, CrustalDecayPlugin*> > LoadFunction::pl_load_map [private]
Referenced by crustalDecayGiven(), getCrustalDecayValueAt(), getHistoryValueAt(), getValueAt(), init(), load(), loadHistoryGiven(), registerOutputFields(), registerParameter(), release(), requestPlugins(), unload(), and ~LoadFunction().
The documentation for this class was generated from the following files:
LoadFunction.h
LoadFunction.cpp