CrusDe: LoadHistoryPlugin Class Reference
LoadHistoryPlugin Class Reference
#include <LoadHistoryPlugin.h>
Public Member Functions
LoadHistoryPlugin (const string=NULL)
virtual ~LoadHistoryPlugin ()
void setJobName (const string)
const string getJobName ()
virtual void load (const string) throw (FileNotFound, LibHandleError)
double getValueAt (unsigned int) throw (LibHandleError)
loadhistory_exec_function getValueFunction () throw (LibHandleError)
Private Member Functions
LoadHistoryPlugin (const LoadHistoryPlugin &x)
Private Attributes
loadhistory_exec_function func_value
string job_name
Constructor & Destructor Documentation
LoadHistoryPlugin::LoadHistoryPlugin (const LoadHistoryPlugin & x) [private]
hidden copy constructor - we do not want to accidentially copy objects
LoadHistoryPlugin::LoadHistoryPlugin (const string _name = NULL)
LoadHistoryPlugin::~LoadHistoryPlugin () [virtual]
References crusde_debug(), and Plugin::name.
Member Function Documentation
const string LoadHistoryPlugin::getJobName ()
References job_name.
double LoadHistoryPlugin::getValueAt (unsigned int time_step) throw (LibHandleError)
loadhistory_exec_function LoadHistoryPlugin::getValueFunction () throw (LibHandleError)
References func_value.
Referenced by SimulationCore::addLoadHistoryPlugin().
void LoadHistoryPlugin::load (const string) throw (FileNotFound, LibHandleError) [virtual]
Reimplemented from Plugin.
References crusde_debug(), and Plugin::load().
Referenced by SimulationCore::addLoadHistoryPlugin().
void LoadHistoryPlugin::setJobName (const string _name)
References job_name.
Member Data Documentation
loadhistory_exec_function LoadHistoryPlugin::func_value [private]
Referenced by getValueFunction().
string LoadHistoryPlugin::job_name [private]
Referenced by getJobName(), and setJobName().
The documentation for this class was generated from the following files:
LoadHistoryPlugin.h
LoadHistoryPlugin.cpp