CrusDe: GreenPlugin Class Reference
GreenPlugin Class Reference
#include <GreenPlugin.h>
Public Member Functions
GreenPlugin (const string=NULL)
virtual ~GreenPlugin ()
virtual void load (const string) throw (FileNotFound, LibHandleError)
int getValueArrayAt (double **, int, int)
green_exec_function getArrayFunction ()
Private Member Functions
GreenPlugin (const GreenPlugin &x)
Private Attributes
map< string, string > my_jobs
green_exec_function func_value_array
Constructor & Destructor Documentation
GreenPlugin::GreenPlugin (const GreenPlugin & x) [private]
hidden copy constructor - we do not want to accidentially copy objects
GreenPlugin::GreenPlugin (const string _name = NULL)
GreenPlugin::~GreenPlugin () [virtual]
References crusde_debug(), and Plugin::name.
Member Function Documentation
green_exec_function GreenPlugin::getArrayFunction ()
References func_value_array.
Referenced by SimulationCore::addGreenPlugin().
int GreenPlugin::getValueArrayAt (double ** result, int x, int y)
References func_value_array, and Plugin::is_initialized.
void GreenPlugin::load (const string new_path) throw (FileNotFound, LibHandleError) [virtual]
Reimplemented from Plugin.
References crusde_debug(), and Plugin::load().
Referenced by SimulationCore::addGreenPlugin(), and GreensFunction::load().
Member Data Documentation
green_exec_function GreenPlugin::func_value_array [private]
Referenced by getArrayFunction(), and getValueArrayAt().
map<string, string> GreenPlugin::my_jobs [private]
The documentation for this class was generated from the following files:
GreenPlugin.h
GreenPlugin.cpp