CrusDe: CrustalDecayPlugin Class Reference
CrustalDecayPlugin Class Reference
#include <CrustalDecayPlugin.h>
Public Member Functions
CrustalDecayPlugin (const string=NULL)
virtual ~CrustalDecayPlugin ()
void setJobName (const string)
const string getJobName ()
virtual void load (const string) throw (FileNotFound, LibHandleError)
double getValueAt (unsigned int) throw (LibHandleError)
crustaldecay_exec_function getValueFunction () throw (LibHandleError)
Private Member Functions
CrustalDecayPlugin (const CrustalDecayPlugin &x)
Private Attributes
crustaldecay_exec_function func_value
string job_name
Constructor & Destructor Documentation
CrustalDecayPlugin::CrustalDecayPlugin (const CrustalDecayPlugin & x) [private]
hidden copy constructor - we do not want to accidentially copy objects
CrustalDecayPlugin::CrustalDecayPlugin (const string _name = NULL)
CrustalDecayPlugin::~CrustalDecayPlugin () [virtual]
References crusde_debug(), and Plugin::name.
Member Function Documentation
const string CrustalDecayPlugin::getJobName ()
References job_name.
double CrustalDecayPlugin::getValueAt (unsigned int time_step) throw (LibHandleError)
crustaldecay_exec_function CrustalDecayPlugin::getValueFunction () throw (LibHandleError)
References func_value.
Referenced by SimulationCore::addCrustalDecayPlugin().
void CrustalDecayPlugin::load (const string) throw (FileNotFound, LibHandleError) [virtual]
Reimplemented from Plugin.
References crusde_debug(), and Plugin::load().
Referenced by SimulationCore::addCrustalDecayPlugin(), and LoadFunction::load().
void CrustalDecayPlugin::setJobName (const string name)
References job_name.
Referenced by LoadFunction::load().
Member Data Documentation
crustaldecay_exec_function CrustalDecayPlugin::func_value [private]
Referenced by getValueFunction().
string CrustalDecayPlugin::job_name [private]
Referenced by getJobName(), and setJobName().
The documentation for this class was generated from the following files:
CrustalDecayPlugin.h
CrustalDecayPlugin.cpp