CrusDe: TreeModel Class Reference
TreeModel Class Reference
#include <Qt_TreeModel.h>
Public Member Functions
TreeModel (const char *id, QObject *parent=0)
~TreeModel ()
QVariant data (const QModelIndex &index, int role) const
Qt::ItemFlags flags (const QModelIndex &index) const
QVariant headerData (int section, Qt::Orientation orientation, int role=Qt::DisplayRole) const
QModelIndex index (int row, int column, const QModelIndex &parent=QModelIndex()) const
QModelIndex parent (const QModelIndex &index) const
int rowCount (const QModelIndex &parent=QModelIndex()) const
int columnCount (const QModelIndex &parent=QModelIndex()) const
void setupModelData (multimap< string, map< int, string > >)
int getID (const QModelIndex &parent=QModelIndex()) const
bool removeRows (int position, int rows, const QModelIndex &parent)
QModelIndex indexOfLatestItem (int id, const QModelIndex &parent=QModelIndex())
Private Attributes
TreeItem * rootItem
Constructor & Destructor Documentation
TreeModel::TreeModel (const char * id, QObject * parent = 0)
References rootItem.
TreeModel::~TreeModel ()
References rootItem.
Member Function Documentation
int TreeModel::columnCount (const QModelIndex & parent = QModelIndex()) const
References TreeItem::columnCount(), and rootItem.
QVariant TreeModel::data (const QModelIndex & index, int role) const
References TreeItem::data().
Referenced by setupModelData().
Qt::ItemFlags TreeModel::flags (const QModelIndex & index) const
int TreeModel::getID (const QModelIndex & parent = QModelIndex()) const
References TreeItem::getID().
Referenced by Dialog::deleteClicked(), indexOfLatestItem(), and Dialog::showDetails().
QVariant TreeModel::headerData (int section, Qt::Orientation orientation, int role = Qt::DisplayRole) const
References TreeItem::data(), and rootItem.
QModelIndex TreeModel::index (int row, int column, const QModelIndex & parent = QModelIndex()) const
References TreeItem::child(), and rootItem.
Referenced by indexOfLatestItem().
QModelIndex TreeModel::indexOfLatestItem (int id, const QModelIndex & parent = QModelIndex())
References TreeItem::child(), getID(), i, index(), and rootItem.
Referenced by Dialog::addClicked().
QModelIndex TreeModel::parent (const QModelIndex & index) const
References TreeItem::parent(), rootItem, and TreeItem::row().
bool TreeModel::removeRows (int position, int rows, const QModelIndex & parent)
References TreeItem::removeChild(), and rootItem.
Referenced by Dialog::deleteClicked().
int TreeModel::rowCount (const QModelIndex & parent = QModelIndex()) const
References TreeItem::childCount(), and rootItem.
void TreeModel::setupModelData (multimap< string, map< int, string > > data)
References TreeItem::appendChild(), data(), i, TreeItem::removeChild(), rootItem, and t.
Referenced by Dialog::setModelData().
Member Data Documentation
TreeItem* TreeModel::rootItem [private]
Referenced by columnCount(), headerData(), index(), indexOfLatestItem(), parent(), removeRows(), rowCount(), setupModelData(), TreeModel(), and ~TreeModel().
The documentation for this class was generated from the following files:
Qt_TreeModel.h
Qt_TreeModel.cpp