CrusDe: XMLCore Class Reference
XMLCore Class Reference
#include <XMLHandler.h>
Public Member Functions
XMLCore ()
~XMLCore ()
Detailed Description
takes care on initialization and termination of Xerces. wrapped in an object to be able to provide "ressource aquisition is initialization" in XMLHandler
Constructor & Destructor Documentation
XMLCore::XMLCore ()
References crusde_warning().
XMLCore::~XMLCore ()
References crusde_debug(), and crusde_warning().
The documentation for this class was generated from the following files:
XMLHandler.h
XMLHandler.cpp