CrusDe: DatabaseManager Class Reference
DatabaseManager Class Reference
#include <DatabaseManager.h>
Public Member Functions
DatabaseManager (const char *path)
virtual ~DatabaseManager ()
virtual void run ()=0
start the manager
virtual void addEntry (string ident, DOMNode *parent=0)=0
add database entry
virtual string getEntryDetails (int)=0
returns a formatted string for display containing all details listed for plugin 'id' in db
virtual multimap< string, map
< int, string > > getEntryMap ()=0
returns a formatted string for display containing all details listed for plugin 'id' in db
virtual bool deleteEntry (int)=0
removes plugin from database. checks before, whether any other plugin depends on ID
virtual void init ()
initialize database
string getDBName ()
returns database name
int getLastAddedID ()
returns last id of an item added to the database
void runDialogWindow (string, bool)
show dialog window;
bool inGuiMode ()
has database manager a Dialog Window open?
Protected Attributes
bool is_initialized
int last_id
Private Member Functions
DatabaseManager (const DatabaseManager &x)
hidden copy constructor - we do not want to accidentially copy objects
Private Attributes
bool guiMode
Detailed Description
manages a database
Constructor & Destructor Documentation
DatabaseManager::DatabaseManager (const DatabaseManager & x) [private]
hidden copy constructor - we do not want to accidentially copy objects
DatabaseManager::DatabaseManager (const char * path)
virtual DatabaseManager::~DatabaseManager () [inline, virtual]
Member Function Documentation
virtual void DatabaseManager::addEntry (string ident, DOMNode * parent = 0) [pure virtual]
add database entry
Implemented in ExperimentManager, and PluginManager.
Referenced by Dialog::addClicked().
virtual bool DatabaseManager::deleteEntry (int) [pure virtual]
removes plugin from database. checks before, whether any other plugin depends on ID
Implemented in ExperimentManager, and PluginManager.
Referenced by Dialog::deleteClicked().
string DatabaseManager::getDBName ()
returns database name
return filename of the database with absolute path
References XMLHandler::xmlFile.
virtual string DatabaseManager::getEntryDetails (int) [pure virtual]
returns a formatted string for display containing all details listed for plugin 'id' in db
Implemented in ExperimentManager, and PluginManager.
Referenced by Dialog::showDetails().
virtual multimap<string, map<int, string> > DatabaseManager::getEntryMap () [pure virtual]
returns a formatted string for display containing all details listed for plugin 'id' in db
Implemented in ExperimentManager, and PluginManager.
Referenced by Dialog::setModelData().
int DatabaseManager::getLastAddedID ()
returns last id of an item added to the database
return id of last entry that's been added to the database
References last_id.
Referenced by Dialog::addClicked().
bool DatabaseManager::inGuiMode ()
has database manager a Dialog Window open?
References guiMode.
void DatabaseManager::init () [virtual]
initialize database
read XML file and read plugins from there into a structured list
Implements XMLHandler.
References is_initialized, and XMLHandler::readXML().
Referenced by SimulationCore::init(), SimulationCore::installPlugin(), SimulationCore::runExperimentManager(), and SimulationCore::runPluginManager().
virtual void DatabaseManager::run () [pure virtual]
start the manager
Implemented in ExperimentManager, and PluginManager.
void DatabaseManager::runDialogWindow (string title, bool addButton)
show dialog window;
create Dialog window and switch into guiMode, run dialog window
References d, and guiMode.
Referenced by PluginManager::run(), and ExperimentManager::run().
Member Data Documentation
bool DatabaseManager::guiMode [private]
Referenced by inGuiMode(), and runDialogWindow().
bool DatabaseManager::is_initialized [protected]
function init() has been called
Referenced by init(), PluginManager::run(), and ExperimentManager::run().
int DatabaseManager::last_id [protected]
Referenced by ExperimentManager::addEntry(), and getLastAddedID().
The documentation for this class was generated from the following files:
DatabaseManager.h
DatabaseManager.cpp