CrusDe: crusde_api.h File Reference
crusde_api.h File Reference
#include "constants.h"
#include "config.h"
#include "stdarg.h"
Defines
#define boolean int
#define true 1
#define false 0
#define NOT_TIME_DEPENDENT false
#define TIME_DEPENDENT true
Enumerations
enum PluginCategory {
LOAD_PLUGIN = 0, KERNEL_PLUGIN = 1, GREEN_PLUGIN = 2, DATAOUT_PLUGIN = 3,
POSTPROCESS_PLUGIN = 4, LOADHISTORY_PLUGIN = 5, CRUSTALDECAY_PLUGIN = 6
}
enum FieldName { X_FIELD = 0, Y_FIELD = 1, Z_FIELD = 2, ADD_FIELD = 3 }
Functions
void crusde_error (const char *format,...)
Prints error message to stderr, exists CrusDe with code ERROR_MSG.
void crusde_debug (const char *format,...)
Prints debug messages to stderr if compiled with -DDEBUG.
void crusde_warning (const char *format,...)
Prints warning message to stderr.
void crusde_info (const char *format,...)
Prints information message to stdout.
double * crusde_register_param_double (const char *param_name, PluginCategory)
double * crusde_register_optional_param_double (const char *param_name, PluginCategory, double)
char ** crusde_register_param_string (const char *param_name, PluginCategory)
char ** crusde_register_optional_param_string (const char *param_name, PluginCategory, char *)
void crusde_register_output_field (int *position, FieldName)
int crusde_get_size_x ()
int crusde_get_size_y ()
int crusde_get_size_t ()
int crusde_get_gridsize ()
int crusde_get_min_x ()
int crusde_get_min_y ()
int crusde_get_dimensions ()
int crusde_get_displacement_dimensions ()
int crusde_model_time ()
int crusde_get_timesteps ()
int crusde_model_step ()
int crusde_stepsize ()
int crusde_get_x_index ()
int crusde_get_y_index ()
int crusde_get_z_index ()
const char * crusde_get_observation_file ()
const char * crusde_get_out_file ()
int crusde_get_green_at (double **res, int x, int y)
double crusde_get_load_at (int x, int y)
double crusde_get_load_history_at (int t)
double crusde_get_crustal_decay_at (int t)
void crusde_set_result (double **)
double ** crusde_get_result ()
void crusde_set_quadrant (int)
int crusde_get_quadrant ()
void crusde_exit (int exitcode)
int crusde_get_current_load_component ()
void crusde_set_current_load_component (int)
int crusde_get_number_of_loads ()
void crusde_set_operator_space (int, int)
void crusde_get_operator_space (int *, int *)
boolean crusde_crustal_decay_given ()
boolean crusde_load_history_given ()
green_exec_function crusde_request_green_plugin (char *plugin)
load_exec_function crusde_request_load_plugin (char *plugin)
run_function crusde_request_kernel_plugin (char *plugin)
run_function crusde_request_postprocessor_plugin (char *plugin)
loadhistory_exec_function crusde_request_loadhistory_plugin (char *plugin)
crustaldecay_exec_function crusde_request_crustaldecay_plugin (char *plugin)
Define Documentation
#define boolean int
#define false 0
#define NOT_TIME_DEPENDENT false
#define TIME_DEPENDENT true
#define true 1
Enumeration Type Documentation
enum FieldName
Enumerator:
X_FIELD
Y_FIELD
Z_FIELD
ADD_FIELD
enum PluginCategory
Enumerator:
LOAD_PLUGIN
KERNEL_PLUGIN
GREEN_PLUGIN
DATAOUT_PLUGIN
POSTPROCESS_PLUGIN
LOADHISTORY_PLUGIN
CRUSTALDECAY_PLUGIN
Function Documentation
boolean crusde_crustal_decay_given ()
References LoadFunction::crustalDecayGiven(), SimulationCore::instance(), and SimulationCore::loadFunction().
Referenced by run().
void crusde_debug (const char * format, ...)
Prints debug messages to stderr if compiled with -DDEBUG.
This function prints a debug message to stderr if CrusDe was compiled with flag -DDEBUG; otherwise nothing is printed; hence debug statements can stay with the code. It is strongly recommended to use this function that works exactly like printf, instead of printf. This way the output of CrusDe is not cluttered with tests and development messages.
Referenced by crusde_register_optional_param_double(), crusde_register_optional_param_string(), crusde_register_param_double(), crusde_register_param_string(), ExperimentManager::ExperimentManager(), InputHandler::getAttributeValue(), InputHandler::getAttributeValueByName(), InputHandler::getGreenJobMap(), InputHandler::getLoadFunctionList(), init(), InputHandler::initParamsFromDOM(), Plugin::load(), LoadPlugin::load(), LoadHistoryPlugin::load(), GreenPlugin::load(), DataOutPlugin::load(), CrustalDecayPlugin::load(), Plugin::Plugin(), PluginManager::PluginManager(), read_alma_output(), InputHandler::readCommandline(), XMLHandler::readXML(), run(), DataOutPlugin::setModelData(), Plugin::unload(), XMLHandler::writeXML(), XMLHandler::XMLHandler(), CrustalDecayPlugin::~CrustalDecayPlugin(), DataOutPlugin::~DataOutPlugin(), GreenPlugin::~GreenPlugin(), InputHandler::~InputHandler(), LoadHistoryPlugin::~LoadHistoryPlugin(), LoadPlugin::~LoadPlugin(), Plugin::~Plugin(), XMLCore::~XMLCore(), and XMLHandler::~XMLHandler().
void crusde_error (const char * format, ...)
Prints error message to stderr, exists CrusDe with code ERROR_MSG.
This function prints an error message to stderr. It works exactly like printf, hence complex message printing is possible. The simulation run will be terminated by calling crusde_exist with the error code ERROR_MSG.
Parameters:
format A formatted string following the sprintf conventions
...
Returns:
void
See also:
crusde_warning(), crusde_info(), crusde_debug(),
References crusde_exit(), and ERROR_MSG.
Referenced by PluginManager::deleteEntry(), InputHandler::getGreenJobMap(), init(), InputHandler::init(), InputHandler::initParamsFromDOM(), SimulationCore::installPlugin(), SimulationCore::instance(), main(), ParamWrapper::newDouble(), ParamWrapper::newString(), InputHandler::readCommandline(), XMLHandler::readXML(), SimulationCore::registerParam(), and ParamWrapper::setValue().
void crusde_exit (int exitcode)
References SimulationCore::instance(), and SimulationCore::terminate().
Referenced by crusde_error(), init(), and read_alma_output().
double crusde_get_crustal_decay_at (int t)
References LoadFunction::getCrustalDecayValueAt(), SimulationCore::instance(), and SimulationCore::loadFunction().
Referenced by run().
int crusde_get_current_load_component ()
References SimulationCore::getLoadFunctionComponent(), and SimulationCore::instance().
Referenced by clear(), get_value_at(), init(), register_parameter(), and set_history_function().
int crusde_get_dimensions ()
References SimulationCore::getDimensions(), and SimulationCore::instance().
Referenced by init(), and run().
int crusde_get_displacement_dimensions ()
References SimulationCore::displacementDimensions(), and SimulationCore::instance().
Referenced by init().
int crusde_get_green_at (double ** res, int x, int y)
References GreensFunction::getValueArrayAt(), SimulationCore::greensFunction(), and SimulationCore::instance().
Referenced by run().
int crusde_get_gridsize ()
References SimulationCore::gridSize(), and SimulationCore::instance().
Referenced by get_value_at(), and init().
double crusde_get_load_at (int x, int y)
References LoadFunction::getValueAt(), SimulationCore::instance(), and SimulationCore::loadFunction().
Referenced by run().
double crusde_get_load_history_at (int t)
References LoadFunction::getHistoryValueAt(), SimulationCore::instance(), and SimulationCore::loadFunction().
Referenced by run().
int crusde_get_min_x ()
References SimulationCore::instance(), and SimulationCore::minX().
Referenced by get_value_at(), and init().
int crusde_get_min_y ()
References SimulationCore::instance(), and SimulationCore::minY().
Referenced by get_value_at(), and init().
int crusde_get_number_of_loads ()
References SimulationCore::getNumberOfLoadComponents(), and SimulationCore::instance().
Referenced by run().
const char* crusde_get_observation_file ()
void crusde_get_operator_space (int * , int *)
References SimulationCore::getOperatorSpaceX(), SimulationCore::getOperatorSpaceY(), and SimulationCore::instance().
const char* crusde_get_out_file ()
References SimulationCore::instance(), and SimulationCore::outFile().
Referenced by init().
int crusde_get_quadrant ()
References SimulationCore::getQuadrant(), and SimulationCore::instance().
Referenced by get_value_at().
double** crusde_get_result ()
References SimulationCore::getModelData(), and SimulationCore::instance().
Referenced by run().
int crusde_get_size_t ()
References SimulationCore::instance(), and SimulationCore::sizeT().
Referenced by init().
int crusde_get_size_x ()
References SimulationCore::instance(), and SimulationCore::sizeX().
Referenced by init().
int crusde_get_size_y ()
References SimulationCore::instance(), and SimulationCore::sizeY().
Referenced by init().
int crusde_get_timesteps ()
References SimulationCore::getTimesteps(), and SimulationCore::instance().
Referenced by init().
int crusde_get_x_index ()
References SimulationCore::instance(), and SimulationCore::xIndex().
Referenced by init(), and run().
int crusde_get_y_index ()
References SimulationCore::instance(), and SimulationCore::yIndex().
Referenced by init(), and run().
int crusde_get_z_index ()
References SimulationCore::instance(), and SimulationCore::zIndex().
Referenced by init(), and run().
void crusde_info (const char * format, ...)
Prints information message to stdout.
This function prints an information message to stderr. It works exactly like printf, hence complex message printing is possible. The simulation run will be continued.
References SimulationCore::instance().
Referenced by SimulationCore::addGreenPlugin(), SimulationCore::exec(), InputHandler::getLoadFunctionList(), InputHandler::getPostProcessorNameList(), SimulationCore::init(), init(), main(), InputHandler::readCommandline(), register_output_fields(), Plugin::registerParameter(), and run().
boolean crusde_load_history_given ()
References SimulationCore::instance(), SimulationCore::loadFunction(), and LoadFunction::loadHistoryGiven().
Referenced by run().
int crusde_model_step ()
References SimulationCore::instance(), and SimulationCore::modelStep().
Referenced by run().
int crusde_model_time ()
References SimulationCore::instance(), and SimulationCore::modelTime().
Referenced by run().
double* crusde_register_optional_param_double (const char * param_name, PluginCategory , double)
References crusde_debug(), SimulationCore::instance(), ParamWrapper::newDouble(), SimulationCore::registerParam(), and ParamWrapper::setOptional().
char** crusde_register_optional_param_string (const char * param_name, PluginCategory , char *)
References crusde_debug(), SimulationCore::instance(), ParamWrapper::newString(), SimulationCore::registerParam(), and ParamWrapper::setOptional().
Referenced by register_parameter().
void crusde_register_output_field (int * position, FieldName)
References SimulationCore::instance(), and SimulationCore::registerOutputField().
Referenced by register_output_fields().
double* crusde_register_param_double (const char * param_name, PluginCategory)
References crusde_debug(), SimulationCore::instance(), ParamWrapper::newDouble(), SimulationCore::registerParam(), and ParamWrapper::setOptional().
Referenced by register_parameter().
char** crusde_register_param_string (const char * param_name, PluginCategory)
References crusde_debug(), SimulationCore::instance(), ParamWrapper::newString(), SimulationCore::registerParam(), and ParamWrapper::setOptional().
Referenced by register_parameter().
crustaldecay_exec_function crusde_request_crustaldecay_plugin (char * plugin)
References SimulationCore::abort(), SimulationCore::addCrustalDecayPlugin(), and SimulationCore::instance().
green_exec_function crusde_request_green_plugin (char * plugin)
References SimulationCore::abort(), SimulationCore::addGreenPlugin(), and SimulationCore::instance().
Referenced by request_plugins().
run_function crusde_request_kernel_plugin (char * plugin)
References SimulationCore::abort(), SimulationCore::addKernelPlugin(), and SimulationCore::instance().
Referenced by request_plugins().
load_exec_function crusde_request_load_plugin (char * plugin)
References SimulationCore::abort(), SimulationCore::addLoadPlugin(), and SimulationCore::instance().
loadhistory_exec_function crusde_request_loadhistory_plugin (char * plugin)
References SimulationCore::abort(), SimulationCore::addLoadHistoryPlugin(), and SimulationCore::instance().
run_function crusde_request_postprocessor_plugin (char * plugin)
References SimulationCore::abort(), SimulationCore::addPostprocessorPlugin(), and SimulationCore::instance().
void crusde_set_current_load_component (int)
References SimulationCore::instance(), and SimulationCore::setLoadFunctionComponent().
Referenced by run().
void crusde_set_operator_space (int , int)
References SimulationCore::instance(), and SimulationCore::setOperatorSpace().
Referenced by init().
void crusde_set_quadrant (int)
References SimulationCore::instance(), and SimulationCore::setQuadrant().
Referenced by run().
void crusde_set_result (double **)
References SimulationCore::instance(), and SimulationCore::setModelData().
Referenced by run().
int crusde_stepsize ()
References SimulationCore::instance(), and SimulationCore::stepSize().
Referenced by init().
void crusde_warning (const char * format, ...)
Prints warning message to stderr.
This function prints a warning message to stderr. It works exactly like printf, hence complex message printing is possible. The simulation run will be continued.
Referenced by ExperimentManager::addEntry(), PluginManager::addToDB(), ExperimentManager::deleteEntry(), Plugin::getCategory(), InputHandler::getLoadFunctionList(), SimulationCore::getRegisteredParameters(), init(), Plugin::init(), InputHandler::init(), InputHandler::initParamsFromDOM(), SimulationCore::installPlugin(), InputHandler::jobExists(), GreensFunction::load(), read_alma_output(), XMLHandler::readXML(), SimulationCore::registerOutputField(), Plugin::registerParameter(), run(), XMLCore::XMLCore(), XMLCore::~XMLCore(), and XMLHandler::~XMLHandler().