CrusDe: main.cpp File Reference
main.cpp File Reference
#include "SimulationCore.h"
#include "constants.h"
#include <map>
#include <time.h>
Functions
int main (int argc, char **argv)
Variables
int const NO_TIME = -1
double const PI = 3.141592653589793
Pi [-].
double const PI_half = PI / 2
Pi half [-].
double const two_PI = PI * 2
two Pi [-]
short const UX = 0
marks x-direction
short const UY = 1
marks y-direction
short const UZ = 2
marks z-direction
int const NOERROR = 0
no error occured
int const ERROR_MSG = -1
error message printed, aborting program
char *const VERSION = "0.2.0"
char *const SVN_REVISION = "r3"
Function Documentation
int main (int argc, char ** argv)
References crusde_error(), crusde_info(), SimulationCore::exec(), SimulationCore::init(), SimulationCore::instance(), and SimulationCore::terminate().
Variable Documentation
int const ERROR_MSG = -1
error message printed, aborting program
Referenced by crusde_error().
int const NO_TIME = -1
Referenced by get_value_at().
int const NOERROR = 0
no error occured
Referenced by get_value_at().
double const PI = 3.141592653589793
Pi [-].
Referenced by get_value_at(), and init().
double const PI_half = PI / 2
Pi half [-].
char* const SVN_REVISION = "r3"
Referenced by version().
double const two_PI = PI * 2
two Pi [-]
short const UX = 0
marks x-direction
short const UY = 1
marks y-direction
short const UZ = 2
marks z-direction
char* const VERSION = "0.2.0"
Referenced by version().