CrusDe: plugin_src/green/pinel_hs_elastic_minus_thickplate.c File Reference
plugin_src/green/pinel_hs_elastic_minus_thickplate.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include "crusde_api.h"
Functions
const char * get_name ()
const char * get_version ()
const char * get_authors ()
PluginCategory get_category ()
const char * get_description ()
void register_parameter ()
Register parameters this Green's function claims from the input.
void register_output_fields ()
Register output fields for spatial directions this Green's function calculates.
void request_plugins ()
void init ()
Initialize members that depend on registered values.
void run ()
Not used in this plugin, left empty!
void clear ()
Clean-up before this plug-in gets unloaded.
int get_value_at (double **result, int x, int y)
Returns the Green's Function value at Point(x,y) at time 0.
Variables
int(* elastic_halfspace)(double **, int, int) = NULL
int(* thick_plate)(double **, int, int) = NULL
int x_pos
int y_pos
int z_pos
Function Documentation
void clear ()
Clean-up before this plug-in gets unloaded.
Yet, there is nothing to free here.
const char* get_authors ()
PluginCategory get_category ()
References GREEN_PLUGIN.
const char* get_description ()
const char* get_name ()
int get_value_at (double ** result, int x, int y)
Returns the Green's Function value at Point(x,y) at time 0.
TODO!
Parameters:
x The x-Coordinate of the wanted value.
y The y-Coordinate of the wanted value.
Returns:
The value found at Point[y][x]
References elastic_halfspace, NOERROR, thick_plate, x_pos, y_pos, and z_pos.
const char* get_version ()
void init ()
Initialize members that depend on registered values.
void register_output_fields ()
Register output fields for spatial directions this Green's function calculates.
References crusde_register_output_field(), X_FIELD, x_pos, Y_FIELD, y_pos, Z_FIELD, and z_pos.
void register_parameter ()
Register parameters this Green's function claims from the input.
void request_plugins ()
References crusde_request_green_plugin(), elastic_halfspace, and thick_plate.
void run ()
Not used in this plugin, left empty!
Variable Documentation
int(* elastic_halfspace)(double **, int, int) = NULL
Referenced by get_value_at(), and request_plugins().
int(* thick_plate)(double **, int, int) = NULL
Referenced by get_value_at(), and request_plugins().
int x_pos
int y_pos
int z_pos