CrusDe: XMLHandler.h File Reference
XMLHandler.h File Reference
#include <xercesc/parsers/XercesDOMParser.hpp>
#include <xercesc/dom/DOM.hpp>
#include <xercesc/dom/DOMDocument.hpp>
#include <xercesc/dom/DOMDocumentType.hpp>
#include <xercesc/dom/DOMElement.hpp>
#include <xercesc/dom/DOMImplementation.hpp>
#include <xercesc/dom/DOMImplementationLS.hpp>
#include <xercesc/dom/DOMNodeIterator.hpp>
#include <xercesc/dom/DOMNodeList.hpp>
#include <xercesc/dom/DOMText.hpp>
#include <xercesc/dom/DOMWriter.hpp>
#include <xercesc/framework/StdOutFormatTarget.hpp>
#include <xercesc/framework/LocalFileFormatTarget.hpp>
#include <xercesc/util/XMLUni.hpp>
#include <xercesc/util/PlatformUtils.hpp>
#include <xercesc/util/XMLString.hpp>
#include <xercesc/util/XMLChar.hpp>
#include <xercesc/util/OutOfMemoryException.hpp>
#include "DOMTreeErrorReporter.hpp"
#include <string>
#include <iostream>
#include <cassert>
#include <dlfcn.h>
#include <stdexcept>
#include <list>
#include <sstream>
#include "exceptions.h"
Classes
class StrXML
class XMLCore
class XMLHandler
Functions
std::string stringify (int x)
Function Documentation
std::string stringify (int x) [inline]
Referenced by ExperimentManager::addEntry(), ExperimentManager::addMetaData(), PluginManager::addToDB(), PluginManager::getEntryById(), and ExperimentManager::getEntryById().